### PR TITLE
add prop open to Task component #51

### PR DESCRIPTION
**Pull request by diego-pascual**

### CODE REVIEW

**Comment by oscarotero** [comment]
@diego-pascual Shoul we include also an event for this? Example:

```js
<Task onToggle={callback} />
```

[More info](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details)

**Comment by diego-pascual** [comment]
@oscarotero added onToggle event

**Comment by pedroparra** [comment]
@diego-pascual @oscarotero Open and onToggle are native props of the details node. These should be passed directly without having to re-declare them. We are using {...props} in these cases.

**Comment by diego-pascual** [comment]
@pedroparra if you put {...props} to a component, non-native properties such as "htmlTitle" will give a warning. Do you know any way to avoid that?
Captura de pantalla 2019-12-03 a las 9 45 @oscarotero src=
@oscarotero

**Comment by oscarotero** [comment]
@diego-pascual I think @pedroparra means to use `...props` only for those remaining properties that are not specific of React. Example:

```jsx
const Task = ({ title, htmlTitle, variant, children, extra, ...props }) => {
    return <details {...props}>
})
```

**Comment by pedroparra** [comment]
@oscarotero Exactly, thanks!
@diego-pascual Perfect

**Pull request merged**
